### ISSUE TITLE
Allow Clerk

### ISSUE THREAD

**Issue by TomSmith27** [loicpennequin/convex-vue#10]
This is amazing however whilst using the library i can't find a way to integrate clerk, Could you include a sample for that?

**Comment by Darialyphia** [comment]
Hello, it's already possible to use clerk with convex-vue, but it's a little bit tricky because `vue-clerk` doesn't allow you to create the clerk instance outside of the VueClerkPlugin. 

I'll try to add a`@convex-vue/clerk` package at some poit. In the meantime, you can get it to work like this :

```ts
import { Ref, computed, createApp, ref } from 'vue';
import { clerkPlugin } from 'vue-clerk/plugin';
import { Resources } from '@clerk/types';

const app = createApp(App).use(clerkPlugin, {
  publishableKey: import.meta.env.VITE_CLERK_PUBLISHABLE_KEY
});

const authState: { isLoading: Ref<boolean>; session: Ref<Resources['session']> } = {
  isLoading: ref(true),
  session: ref(undefined)
};
app.config.globalProperties.$clerk.addListener(arg => {
  authState.isLoading.value = false;
  authState.session.value = arg.session;
});

const convexVue = createConvexVue({
  convexUrl: import.meta.env.VITE_CONVEX_URL,
  auth: {
    isAuthenticated: computed(() => !!authState.session.value),
    isLoading: authState.isLoading,
    getToken: async ({ forceRefreshToken }) => {
      try {
        return await authState.session.value?.getToken({
          template: 'convex',
          skipCache: forceRefreshToken
        });
      } catch (error) {
        return null;
      }
    },
  }
});

app.use(convexVue).mount('#app');
```

This will enable you to sync clerk with `useConvexAuth()`

**Comment by TomSmith27** [comment]
Ah amazing thanks for this! Couldn't figure out how to get the clerk state into the Auth object

**Comment by ssorallen** [comment]
@loicpennequin I added your comment to the README: https://github.com/loicpennequin/convex-vue/pull/13
