### ISSUE TITLE
Types point to incorrect file

### ISSUE THREAD

**Issue by ssorallen** [loicpennequin/convex-vue#6]
After doing `npm install @convex-vue/core` it looks as if the package is pointing to the incorrect type file.

Structure in node_modules after install:
<img width="189" alt="Screenshot 2024-03-11 at 6 00 28 PM" src="https://github.com/loicpennequin/convex-vue/assets/29612/0c6e9b85-5d3c-4c33-ad30-ce65ba7c24c1">

Attempt to import from `"@convex-vue/core"`:
<img width="385" alt="Screenshot 2024-03-11 at 6 00 18 PM" src="https://github.com/loicpennequin/convex-vue/assets/29612/4fea30c1-80fb-48e9-b16f-ffce784cf08e">

File that opens with Cmd+click on the `"@convex-vue/core"` import:
<img width="479" alt="Screenshot 2024-03-11 at 6 00 38 PM" src="https://github.com/loicpennequin/convex-vue/assets/29612/2fd88811-f6e5-498b-a745-70ebe322a930">

The correct file appears to be one level up inside dist/.

**Comment by Darialyphia** [comment]
Hi, thank you for noticing ! I updated the package.json to point to the correct path for the types declarations, it should work properly now. 

However I'm a bit confused because it already worked for me before (I got correct types and ctrl+clicking took me to the correct file).

**Comment by ssorallen** [comment]
@loicpennequin Strange, had you been doing `npm link` to test the package maybe? I'll try switching to the NPM package now. So far we have been using this repo as a submodule but an NPM package will be great instead.

**Comment by ssorallen** [comment]
This looks good in v0.0.3. Closing this one.
