### ISSUE TITLE
Remove dependency on auth0

### ISSUE THREAD

**Issue by ssorallen** [loicpennequin/convex-vue#9]
auth0 is required only if you want to use the auth0-related components, but it is currently listed in `dependencies` and so is always installed. It would be nice to move those components into `@convex-use/auth0` or something similar so the core does not require any specific auth library.

**Comment by ssorallen** [comment]
The Convex usage could maybe move it a separate package too? and list `@convex-vue/use` in its `peerDependencies`.

**Comment by Darialyphia** [comment]
Yep you're right ! Auth0 was only installed to be used in the playground of @convex-vue/core. It has been moved to dev dependencies

**Comment by ssorallen** [comment]
@loicpennequin Amazing, thanks!
